from tkinter import *
import tkinter as tk
from tkinter import ttk
from PIL import ImageTk,Image
def ajuda():
    janela_ajuda = tk.Toplevel()
    janela_ajuda.title("Ajuda")
    janela_ajuda.geometry("1000x1000")
    Info = Label(janela_ajuda,text= "Explicação do funcionamento de cada botão")
    Info.pack(padx=10,pady=10)
    nb=ttk.Notebook(janela_ajuda,width=1000,height=900)
    nb.pack(padx=10,pady=10)
    funcionamento = Frame(nb)
    nb.add(funcionamento,text="Funcionamento do Programa")

    label_funcionamento = Label(funcionamento, text="Esse Programa simula uma memória de um computador.\nVocê poderá alocar processos em uma memória com até 100 blocos de memória\nOs processos serão criadas em ordem alfabética, e cores aleatórias.\nVocê poderá desalocar um processo especifico da memória dizendo apenas o Nome dele(letra).\nO programa possue um botão limpar processos que ao ser clicado, apagará tudo o que tiver na memória.\nConforme o uso do programa uma memória com espaços vazios nos endereços menores poderá ficar lenta.\nEntão o programa possue um botão chamado realocar que toda vez clicado,\nRealocará um bloco de processos até o inicio da memória")
    label_funcionamento.pack(pady=70,anchor=CENTER, fill="both")
    label_criadores = Label(funcionamento,text= "Esse programa foi desenvolvido por: Guilherme Penso, Matheus Guilherme, Murilo Lustosa e Emanoel Andre.")
    label_criadores.pack(padx=10,pady=10)
    label_criadores.config(font="Arial 12")
    Alocar= Frame(nb)
    label_info=Label(Alocar,text="Funcionamento do Botão Alocar.")
    label_info.pack(padx=10,pady=10)
    label_imagealocar1=Label(Alocar,text="",image=imagem_alocar1)
    label_imagealocar1.pack(padx=10,pady=10)
    mensagealocar= Label(Alocar,text="A Memória estará em branco.")
    mensagealocar.pack()
    label_gridalocar=Label(Alocar,text="",image=imagem_gridbranco)
    label_gridalocar.pack()
    mensagealocar2=Label(Alocar,text="Após o clicar no botão Alocar, abrirá a seguinte aba, que adicionarei um processo de tamanho 5, como exemplo.")
    mensagealocar2.pack()
    label_imagemalocar2=Label(Alocar,text="",image=imagem_alocar2)
    label_imagemalocar2.pack()
    mensagealocar3=Label(Alocar,text="Após clicar OK,a Memória adicionará um processo com 5 blocos, com o nome 'A'.")
    mensagealocar3.pack()
    label_imagemalocar3=Label(Alocar,text="",image=imagem_alocar3)
    label_imagemalocar3.pack()
    nb.add(Alocar,text ="Alocar")

    Desalocar = Frame(nb)
    label_info2 = Label(Desalocar, text="Funcionamento do Botão Desalocar.")
    label_info2.pack(padx=10, pady=10)
    label_imagedesalocar1 = Label(Desalocar, text="", image=imagem_desalocar1)
    label_imagedesalocar1.pack(padx=10, pady=10)
    mensagedesalocar = Label(Desalocar, text="A Memória estará com um processo 'B' com o tamanho de 7 blocos.")
    mensagedesalocar.pack()
    label_griddesalocar = Label(Desalocar, text="", image=imagem_desalocar2)
    label_griddesalocar.pack()
    mensagedesalocar2 = Label(Desalocar,
                           text="Após clicar no botão Desalocar, abrirá a seguinte aba, que digitariei o Nome do processo que quero remover, o processo neste caso, é o Processo 'B'.")
    mensagedesalocar2.pack()
    label_imagemdesalocar2 = Label(Desalocar, text="", image=imagem_desalocar3)
    label_imagemdesalocar2.pack()
    mensagedesalocar3 = Label(Desalocar, text="Após clicar OK,a Memória removerá o Processo digitado.")
    mensagedesalocar3.pack()
    label_imagemdesalocar3 = Label(Desalocar, text="", image=imagem_gridbranco)
    label_imagemdesalocar3.pack()
    nb.add(Desalocar,text="Desalocar")

    Desalocar_tudo = Frame(nb)
    label_info3 = Label(Desalocar_tudo, text="Funcionamento do Botão Limpar Processos.")
    label_info3.pack(padx=10, pady=10)
    label_imagelimpar1 = Label(Desalocar_tudo, text="", image=imagem_limpar1)
    label_imagelimpar1.pack(padx=10, pady=10)
    mensagelimpar1 = Label(Desalocar_tudo, text="A Memória com algums processos:")
    mensagelimpar1.pack()
    label_imagelimpar2 = Label(Desalocar_tudo, text="", image=imagem_limpar2)
    label_imagelimpar2.pack()
    mensagalimpar3 = Label(Desalocar_tudo,text="Após você clique no botão Limpar Processos, a Memória apagará tudo, exemplo abaixo:")
    mensagalimpar3.pack()
    label_imagegrid = Label(Desalocar_tudo,text="",image=imagem_gridbranco)
    label_imagegrid.pack()
    nb.add(Desalocar_tudo,text= "Limpar Processos")

    Realocar = Frame(nb)
    label_info4 = Label(Realocar, text="Funcionamento do Botão Limpar Processos.")
    label_info4.pack(padx=10, pady=10)
    label_Realocar1 = Label(Realocar, text="", image=imagem_realocar1)
    label_Realocar1.pack(padx=10, pady=10)
    mensageRealocar1 = Label(Realocar, text="A Memória com algums processos, e um endereço livre, para melhorar o desempenho da memória você clica em Realocar")
    mensageRealocar1.pack()
    label_Realocar2 = Label(Realocar,text="",image=imagem_realocar2)
    label_Realocar2.pack()
    mensageRealocar2 = Label(Realocar,text="Após Clicar no botão Realocar,o primeiro Processo encontrado irá para o começo da memória como no exemplo abaixo: ")
    mensageRealocar2.pack()
    label_Realocar3 = Label(Realocar,text="",image=imagem_realocar3)
    label_Realocar3.pack()
    mensageRealocar3 = Label(Realocar,text=" Você pode realocar toda vez que desejar. ")
    mensageRealocar3.pack()
    nb.add(Realocar, text="Realocar")

app = tk.Tk()
app.title("teste")
app.geometry("600x300")
buttom = Button(text="Ajuda",command=ajuda)
buttom.pack()

imagem_gridbranco=ImageTk.PhotoImage(Image.open("grid.png"))
imagem_alocar1=ImageTk.PhotoImage(Image.open("alocar1.png"))
imagem_alocar2=ImageTk.PhotoImage(Image.open("alocar2.png"))
imagem_alocar3=ImageTk.PhotoImage(Image.open("alocar3.png"))
imagem_desalocar1=ImageTk.PhotoImage(Image.open("desalocar1.png"))
imagem_desalocar2=ImageTk.PhotoImage(Image.open("desalocar2.png"))
imagem_desalocar3=ImageTk.PhotoImage(Image.open("desalocar3.png"))
imagem_limpar1=ImageTk.PhotoImage(Image.open("limpar1.png"))
imagem_limpar2=ImageTk.PhotoImage(Image.open("limpar2.png"))
imagem_realocar1=ImageTk.PhotoImage(Image.open("realocar1.png"))
imagem_realocar2=ImageTk.PhotoImage(Image.open("realocar2.png"))
imagem_realocar3=ImageTk.PhotoImage(Image.open("realocar3.png"))


app.mainloop()