# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'memorymanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 631)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Alocar = QtWidgets.QPushButton(self.centralwidget)
        self.Alocar.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.Alocar.setObjectName("Alocar")
        self.Apagar = QtWidgets.QPushButton(self.centralwidget)
        self.Apagar.setGeometry(QtCore.QRect(10, 70, 101, 51))
        self.Apagar.setObjectName("Apagar")
        self.Realocar = QtWidgets.QPushButton(self.centralwidget)
        self.Realocar.setGeometry(QtCore.QRect(10, 130, 101, 51))
        self.Realocar.setObjectName("Realocar")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(120, 10, 771, 561))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Alocar.setText(_translate("MainWindow", "Alocar Memória"))
        self.Apagar.setText(_translate("MainWindow", "Apagar Memória"))
        self.Realocar.setText(_translate("MainWindow", "Realocar Memória"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
